export const Cursos = [
    {
        dataId: 1,
        nombre: 'HTML, CSS y JavaScript para principiantes',
        autor: 'José Luis',
        image:'/curso01.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 2,
        nombre: 'Curso de Comida Vegetariana',
        autor: 'Jorge Alejandro',
        image:'/curso02.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 3,
        nombre: 'Guitarra para principiantes',
        autor: 'Eduardo García',
        image:'/curso03.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 4,
        nombre: 'Huerto en casa',
        autor: 'Emilia Cortés',
        image:'/curso04.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 5,
        nombre: 'Decoración con productos de tu casa',
        autor: 'Carlos Vega',
        image:'/curso05.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 6,
        nombre: 'Diseño Web para principiantes',
        autor: 'José Luis',
        image:'/curso01.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 7,
        nombre: 'Comida Mexicana para principiantes',
        autor: 'Camila Vega',
        image:'/curso02.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 8,
        nombre: 'Estudio Musical en tu casa',
        autor: 'Juan Pedro',
        image:'/curso03.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 9,
        nombre: 'Cosecha tus propias frutas y verduras',
        autor: 'Jorge Alejandro',
        image:'/curso04.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 10,
        nombre: 'Prepara galletas caseras',
        autor: 'Paola Vega',
        image:'/curso05.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 11,
        nombre: 'JavaScript moderno con ES6',
        autor: 'Manuel Salazar',
        image:'/curso01.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },
    {
        dataId: 12,
        nombre: '100 Recetas de comida natural',
        autor: 'Mercedes Cortés',
        image:'/curso02.jpg',
        precioOriginal: '$200',
        precioDescuento: '$15',
    },

]